version: "1"

services:
  frontend:
    build: ./services/front_end
    volumes:
      - "./services/front_end:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    command: pnpm dev
    environment:
      NODE_ENV: development
  backend:
    build: ./services/back_end
    ports:
      - 5001:5001
    # environment:
    #   - DATABASE_URL=postgres://hello_fastapi:hello_fastapi@db:5432/hello_fastapi_dev
    #   - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    volumes:
      - ./services/back_end:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5001
