version: '1'

services:
  frontend:
    build: ./services/front_end
    volumes:
      - './services/front_end:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    command: yarn dev
    environment:
      NODE_ENV: development


